# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 021e301575d2fb264f10ab5c6d7a571a07bbf58a0fd69d8fda8c258430751f25a99f73a9ae28a8aecb70efb558d0b36d9a186792063754e9cf0f1955f080bbc3

test:
  secret_key_base: f0b7ca3e2db0e7d0b8be12b22feb8fe99e5575388bbf76c23be5dab3b4f00c3145de8b86883adad057552c3d09654a164b2b1dbf3287ca62390049eff41c08dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
